/*
 * Riot API
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - Routes Table: [`routesTable.json`](../routesTable.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: 879affafe206ccc5b48127e68c0bd466fcc73c84
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.pajonti.sejuapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ValContentV1LocalizedNamesDto
 */
public class ValContentV1LocalizedNamesDtoTest {
    private final ValContentV1LocalizedNamesDto model = new ValContentV1LocalizedNamesDto();

    /**
     * Model tests for ValContentV1LocalizedNamesDto
     */
    @Test
    public void testValContentV1LocalizedNamesDto() {
        // TODO: test ValContentV1LocalizedNamesDto
    }

    /**
     * Test the property 'arAE'
     */
    @Test
    public void arAETest() {
        // TODO: test arAE
    }

    /**
     * Test the property 'deDE'
     */
    @Test
    public void deDETest() {
        // TODO: test deDE
    }

    /**
     * Test the property 'enGB'
     */
    @Test
    public void enGBTest() {
        // TODO: test enGB
    }

    /**
     * Test the property 'enUS'
     */
    @Test
    public void enUSTest() {
        // TODO: test enUS
    }

    /**
     * Test the property 'esES'
     */
    @Test
    public void esESTest() {
        // TODO: test esES
    }

    /**
     * Test the property 'esMX'
     */
    @Test
    public void esMXTest() {
        // TODO: test esMX
    }

    /**
     * Test the property 'frFR'
     */
    @Test
    public void frFRTest() {
        // TODO: test frFR
    }

    /**
     * Test the property 'idID'
     */
    @Test
    public void idIDTest() {
        // TODO: test idID
    }

    /**
     * Test the property 'itIT'
     */
    @Test
    public void itITTest() {
        // TODO: test itIT
    }

    /**
     * Test the property 'jaJP'
     */
    @Test
    public void jaJPTest() {
        // TODO: test jaJP
    }

    /**
     * Test the property 'koKR'
     */
    @Test
    public void koKRTest() {
        // TODO: test koKR
    }

    /**
     * Test the property 'plPL'
     */
    @Test
    public void plPLTest() {
        // TODO: test plPL
    }

    /**
     * Test the property 'ptBR'
     */
    @Test
    public void ptBRTest() {
        // TODO: test ptBR
    }

    /**
     * Test the property 'ruRU'
     */
    @Test
    public void ruRUTest() {
        // TODO: test ruRU
    }

    /**
     * Test the property 'thTH'
     */
    @Test
    public void thTHTest() {
        // TODO: test thTH
    }

    /**
     * Test the property 'trTR'
     */
    @Test
    public void trTRTest() {
        // TODO: test trTR
    }

    /**
     * Test the property 'viVN'
     */
    @Test
    public void viVNTest() {
        // TODO: test viVN
    }

    /**
     * Test the property 'zhCN'
     */
    @Test
    public void zhCNTest() {
        // TODO: test zhCN
    }

    /**
     * Test the property 'zhTW'
     */
    @Test
    public void zhTWTest() {
        // TODO: test zhTW
    }

}
