/*
 * Riot API
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - Routes Table: [`routesTable.json`](../routesTable.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: 879affafe206ccc5b48127e68c0bd466fcc73c84
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.pajonti.sejuapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.pajonti.sejuapi.model.LolChallengesV1ChallengeInfo;
import fr.pajonti.sejuapi.model.LolChallengesV1ChallengePoints;
import fr.pajonti.sejuapi.model.LolChallengesV1PlayerClientPreferences;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import fr.pajonti.sejuapi.invoker.JSON;

/**
 * LolChallengesV1PlayerInfoDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-14T18:28:23.553111400+01:00[Europe/Paris]", comments = "Generator version: 7.4.0")
public class LolChallengesV1PlayerInfoDto {
  public static final String SERIALIZED_NAME_CHALLENGES = "challenges";
  @SerializedName(SERIALIZED_NAME_CHALLENGES)
  private List<LolChallengesV1ChallengeInfo> challenges = new ArrayList<>();

  public static final String SERIALIZED_NAME_PREFERENCES = "preferences";
  @SerializedName(SERIALIZED_NAME_PREFERENCES)
  private LolChallengesV1PlayerClientPreferences preferences;

  public static final String SERIALIZED_NAME_TOTAL_POINTS = "totalPoints";
  @SerializedName(SERIALIZED_NAME_TOTAL_POINTS)
  private LolChallengesV1ChallengePoints totalPoints;

  public static final String SERIALIZED_NAME_CATEGORY_POINTS = "categoryPoints";
  @SerializedName(SERIALIZED_NAME_CATEGORY_POINTS)
  private Map<String, LolChallengesV1ChallengePoints> categoryPoints = new HashMap<>();

  public LolChallengesV1PlayerInfoDto() {
  }

  public LolChallengesV1PlayerInfoDto challenges(List<LolChallengesV1ChallengeInfo> challenges) {
    this.challenges = challenges;
    return this;
  }

  public LolChallengesV1PlayerInfoDto addChallengesItem(LolChallengesV1ChallengeInfo challengesItem) {
    if (this.challenges == null) {
      this.challenges = new ArrayList<>();
    }
    this.challenges.add(challengesItem);
    return this;
  }

   /**
   * Get challenges
   * @return challenges
  **/
  @javax.annotation.Nonnull
  public List<LolChallengesV1ChallengeInfo> getChallenges() {
    return challenges;
  }

  public void setChallenges(List<LolChallengesV1ChallengeInfo> challenges) {
    this.challenges = challenges;
  }


  public LolChallengesV1PlayerInfoDto preferences(LolChallengesV1PlayerClientPreferences preferences) {
    this.preferences = preferences;
    return this;
  }

   /**
   * Get preferences
   * @return preferences
  **/
  @javax.annotation.Nonnull
  public LolChallengesV1PlayerClientPreferences getPreferences() {
    return preferences;
  }

  public void setPreferences(LolChallengesV1PlayerClientPreferences preferences) {
    this.preferences = preferences;
  }


  public LolChallengesV1PlayerInfoDto totalPoints(LolChallengesV1ChallengePoints totalPoints) {
    this.totalPoints = totalPoints;
    return this;
  }

   /**
   * Get totalPoints
   * @return totalPoints
  **/
  @javax.annotation.Nonnull
  public LolChallengesV1ChallengePoints getTotalPoints() {
    return totalPoints;
  }

  public void setTotalPoints(LolChallengesV1ChallengePoints totalPoints) {
    this.totalPoints = totalPoints;
  }


  public LolChallengesV1PlayerInfoDto categoryPoints(Map<String, LolChallengesV1ChallengePoints> categoryPoints) {
    this.categoryPoints = categoryPoints;
    return this;
  }

  public LolChallengesV1PlayerInfoDto putCategoryPointsItem(String key, LolChallengesV1ChallengePoints categoryPointsItem) {
    if (this.categoryPoints == null) {
      this.categoryPoints = new HashMap<>();
    }
    this.categoryPoints.put(key, categoryPointsItem);
    return this;
  }

   /**
   * Get categoryPoints
   * @return categoryPoints
  **/
  @javax.annotation.Nonnull
  public Map<String, LolChallengesV1ChallengePoints> getCategoryPoints() {
    return categoryPoints;
  }

  public void setCategoryPoints(Map<String, LolChallengesV1ChallengePoints> categoryPoints) {
    this.categoryPoints = categoryPoints;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LolChallengesV1PlayerInfoDto lolChallengesV1PlayerInfoDto = (LolChallengesV1PlayerInfoDto) o;
    return Objects.equals(this.challenges, lolChallengesV1PlayerInfoDto.challenges) &&
        Objects.equals(this.preferences, lolChallengesV1PlayerInfoDto.preferences) &&
        Objects.equals(this.totalPoints, lolChallengesV1PlayerInfoDto.totalPoints) &&
        Objects.equals(this.categoryPoints, lolChallengesV1PlayerInfoDto.categoryPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(challenges, preferences, totalPoints, categoryPoints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LolChallengesV1PlayerInfoDto {\n");
    sb.append("    challenges: ").append(toIndentedString(challenges)).append("\n");
    sb.append("    preferences: ").append(toIndentedString(preferences)).append("\n");
    sb.append("    totalPoints: ").append(toIndentedString(totalPoints)).append("\n");
    sb.append("    categoryPoints: ").append(toIndentedString(categoryPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("challenges");
    openapiFields.add("preferences");
    openapiFields.add("totalPoints");
    openapiFields.add("categoryPoints");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("challenges");
    openapiRequiredFields.add("preferences");
    openapiRequiredFields.add("totalPoints");
    openapiRequiredFields.add("categoryPoints");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to LolChallengesV1PlayerInfoDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LolChallengesV1PlayerInfoDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LolChallengesV1PlayerInfoDto is not found in the empty JSON string", LolChallengesV1PlayerInfoDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LolChallengesV1PlayerInfoDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LolChallengesV1PlayerInfoDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : LolChallengesV1PlayerInfoDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("challenges").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `challenges` to be an array in the JSON string but got `%s`", jsonObj.get("challenges").toString()));
      }

      JsonArray jsonArraychallenges = jsonObj.getAsJsonArray("challenges");
      // validate the required field `challenges` (array)
      for (int i = 0; i < jsonArraychallenges.size(); i++) {
        LolChallengesV1ChallengeInfo.validateJsonElement(jsonArraychallenges.get(i));
      };
      // validate the required field `preferences`
      LolChallengesV1PlayerClientPreferences.validateJsonElement(jsonObj.get("preferences"));
      // validate the required field `totalPoints`
      LolChallengesV1ChallengePoints.validateJsonElement(jsonObj.get("totalPoints"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LolChallengesV1PlayerInfoDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LolChallengesV1PlayerInfoDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LolChallengesV1PlayerInfoDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LolChallengesV1PlayerInfoDto.class));

       return (TypeAdapter<T>) new TypeAdapter<LolChallengesV1PlayerInfoDto>() {
           @Override
           public void write(JsonWriter out, LolChallengesV1PlayerInfoDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LolChallengesV1PlayerInfoDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LolChallengesV1PlayerInfoDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LolChallengesV1PlayerInfoDto
  * @throws IOException if the JSON string is invalid with respect to LolChallengesV1PlayerInfoDto
  */
  public static LolChallengesV1PlayerInfoDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LolChallengesV1PlayerInfoDto.class);
  }

 /**
  * Convert an instance of LolChallengesV1PlayerInfoDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

