/*
 * Riot API
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - Routes Table: [`routesTable.json`](../routesTable.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: 879affafe206ccc5b48127e68c0bd466fcc73c84
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.pajonti.sejuapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.pajonti.sejuapi.model.MatchV5ObjectiveDto;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import fr.pajonti.sejuapi.invoker.JSON;

/**
 * MatchV5ObjectivesDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-14T18:28:23.553111400+01:00[Europe/Paris]", comments = "Generator version: 7.4.0")
public class MatchV5ObjectivesDto {
  public static final String SERIALIZED_NAME_BARON = "baron";
  @SerializedName(SERIALIZED_NAME_BARON)
  private MatchV5ObjectiveDto baron;

  public static final String SERIALIZED_NAME_CHAMPION = "champion";
  @SerializedName(SERIALIZED_NAME_CHAMPION)
  private MatchV5ObjectiveDto champion;

  public static final String SERIALIZED_NAME_DRAGON = "dragon";
  @SerializedName(SERIALIZED_NAME_DRAGON)
  private MatchV5ObjectiveDto dragon;

  public static final String SERIALIZED_NAME_INHIBITOR = "inhibitor";
  @SerializedName(SERIALIZED_NAME_INHIBITOR)
  private MatchV5ObjectiveDto inhibitor;

  public static final String SERIALIZED_NAME_RIFT_HERALD = "riftHerald";
  @SerializedName(SERIALIZED_NAME_RIFT_HERALD)
  private MatchV5ObjectiveDto riftHerald;

  public static final String SERIALIZED_NAME_TOWER = "tower";
  @SerializedName(SERIALIZED_NAME_TOWER)
  private MatchV5ObjectiveDto tower;

  public static final String SERIALIZED_NAME_HORDE = "horde";
  @SerializedName(SERIALIZED_NAME_HORDE)
  private MatchV5ObjectiveDto horde;

  public MatchV5ObjectivesDto() {
  }

  public MatchV5ObjectivesDto baron(MatchV5ObjectiveDto baron) {
    this.baron = baron;
    return this;
  }

   /**
   * Get baron
   * @return baron
  **/
  @javax.annotation.Nonnull
  public MatchV5ObjectiveDto getBaron() {
    return baron;
  }

  public void setBaron(MatchV5ObjectiveDto baron) {
    this.baron = baron;
  }


  public MatchV5ObjectivesDto champion(MatchV5ObjectiveDto champion) {
    this.champion = champion;
    return this;
  }

   /**
   * Get champion
   * @return champion
  **/
  @javax.annotation.Nonnull
  public MatchV5ObjectiveDto getChampion() {
    return champion;
  }

  public void setChampion(MatchV5ObjectiveDto champion) {
    this.champion = champion;
  }


  public MatchV5ObjectivesDto dragon(MatchV5ObjectiveDto dragon) {
    this.dragon = dragon;
    return this;
  }

   /**
   * Get dragon
   * @return dragon
  **/
  @javax.annotation.Nonnull
  public MatchV5ObjectiveDto getDragon() {
    return dragon;
  }

  public void setDragon(MatchV5ObjectiveDto dragon) {
    this.dragon = dragon;
  }


  public MatchV5ObjectivesDto inhibitor(MatchV5ObjectiveDto inhibitor) {
    this.inhibitor = inhibitor;
    return this;
  }

   /**
   * Get inhibitor
   * @return inhibitor
  **/
  @javax.annotation.Nonnull
  public MatchV5ObjectiveDto getInhibitor() {
    return inhibitor;
  }

  public void setInhibitor(MatchV5ObjectiveDto inhibitor) {
    this.inhibitor = inhibitor;
  }


  public MatchV5ObjectivesDto riftHerald(MatchV5ObjectiveDto riftHerald) {
    this.riftHerald = riftHerald;
    return this;
  }

   /**
   * Get riftHerald
   * @return riftHerald
  **/
  @javax.annotation.Nonnull
  public MatchV5ObjectiveDto getRiftHerald() {
    return riftHerald;
  }

  public void setRiftHerald(MatchV5ObjectiveDto riftHerald) {
    this.riftHerald = riftHerald;
  }


  public MatchV5ObjectivesDto tower(MatchV5ObjectiveDto tower) {
    this.tower = tower;
    return this;
  }

   /**
   * Get tower
   * @return tower
  **/
  @javax.annotation.Nonnull
  public MatchV5ObjectiveDto getTower() {
    return tower;
  }

  public void setTower(MatchV5ObjectiveDto tower) {
    this.tower = tower;
  }


  public MatchV5ObjectivesDto horde(MatchV5ObjectiveDto horde) {
    this.horde = horde;
    return this;
  }

   /**
   * Get horde
   * @return horde
  **/
  @javax.annotation.Nullable
  public MatchV5ObjectiveDto getHorde() {
    return horde;
  }

  public void setHorde(MatchV5ObjectiveDto horde) {
    this.horde = horde;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchV5ObjectivesDto matchV5ObjectivesDto = (MatchV5ObjectivesDto) o;
    return Objects.equals(this.baron, matchV5ObjectivesDto.baron) &&
        Objects.equals(this.champion, matchV5ObjectivesDto.champion) &&
        Objects.equals(this.dragon, matchV5ObjectivesDto.dragon) &&
        Objects.equals(this.inhibitor, matchV5ObjectivesDto.inhibitor) &&
        Objects.equals(this.riftHerald, matchV5ObjectivesDto.riftHerald) &&
        Objects.equals(this.tower, matchV5ObjectivesDto.tower) &&
        Objects.equals(this.horde, matchV5ObjectivesDto.horde);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baron, champion, dragon, inhibitor, riftHerald, tower, horde);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchV5ObjectivesDto {\n");
    sb.append("    baron: ").append(toIndentedString(baron)).append("\n");
    sb.append("    champion: ").append(toIndentedString(champion)).append("\n");
    sb.append("    dragon: ").append(toIndentedString(dragon)).append("\n");
    sb.append("    inhibitor: ").append(toIndentedString(inhibitor)).append("\n");
    sb.append("    riftHerald: ").append(toIndentedString(riftHerald)).append("\n");
    sb.append("    tower: ").append(toIndentedString(tower)).append("\n");
    sb.append("    horde: ").append(toIndentedString(horde)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("baron");
    openapiFields.add("champion");
    openapiFields.add("dragon");
    openapiFields.add("inhibitor");
    openapiFields.add("riftHerald");
    openapiFields.add("tower");
    openapiFields.add("horde");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("baron");
    openapiRequiredFields.add("champion");
    openapiRequiredFields.add("dragon");
    openapiRequiredFields.add("inhibitor");
    openapiRequiredFields.add("riftHerald");
    openapiRequiredFields.add("tower");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to MatchV5ObjectivesDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MatchV5ObjectivesDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MatchV5ObjectivesDto is not found in the empty JSON string", MatchV5ObjectivesDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MatchV5ObjectivesDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MatchV5ObjectivesDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MatchV5ObjectivesDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `baron`
      MatchV5ObjectiveDto.validateJsonElement(jsonObj.get("baron"));
      // validate the required field `champion`
      MatchV5ObjectiveDto.validateJsonElement(jsonObj.get("champion"));
      // validate the required field `dragon`
      MatchV5ObjectiveDto.validateJsonElement(jsonObj.get("dragon"));
      // validate the required field `inhibitor`
      MatchV5ObjectiveDto.validateJsonElement(jsonObj.get("inhibitor"));
      // validate the required field `riftHerald`
      MatchV5ObjectiveDto.validateJsonElement(jsonObj.get("riftHerald"));
      // validate the required field `tower`
      MatchV5ObjectiveDto.validateJsonElement(jsonObj.get("tower"));
      // validate the optional field `horde`
      if (jsonObj.get("horde") != null && !jsonObj.get("horde").isJsonNull()) {
        MatchV5ObjectiveDto.validateJsonElement(jsonObj.get("horde"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MatchV5ObjectivesDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MatchV5ObjectivesDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MatchV5ObjectivesDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MatchV5ObjectivesDto.class));

       return (TypeAdapter<T>) new TypeAdapter<MatchV5ObjectivesDto>() {
           @Override
           public void write(JsonWriter out, MatchV5ObjectivesDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MatchV5ObjectivesDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MatchV5ObjectivesDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MatchV5ObjectivesDto
  * @throws IOException if the JSON string is invalid with respect to MatchV5ObjectivesDto
  */
  public static MatchV5ObjectivesDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MatchV5ObjectivesDto.class);
  }

 /**
  * Convert an instance of MatchV5ObjectivesDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

