/*
 * Riot API
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - Routes Table: [`routesTable.json`](../routesTable.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: 879affafe206ccc5b48127e68c0bd466fcc73c84
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.pajonti.sejuapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.pajonti.sejuapi.model.MatchV5MatchTimelineInfoFrameParticipantFrame;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import fr.pajonti.sejuapi.invoker.JSON;

/**
 * MatchV5MatchTimelineInfoFrameParticipantFrames
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-14T18:28:23.553111400+01:00[Europe/Paris]", comments = "Generator version: 7.4.0")
public class MatchV5MatchTimelineInfoFrameParticipantFrames {
  public static final String SERIALIZED_NAME_1 = "1";
  @SerializedName(SERIALIZED_NAME_1)
  private MatchV5MatchTimelineInfoFrameParticipantFrame _1;

  public static final String SERIALIZED_NAME_2 = "2";
  @SerializedName(SERIALIZED_NAME_2)
  private MatchV5MatchTimelineInfoFrameParticipantFrame _2;

  public static final String SERIALIZED_NAME_3 = "3";
  @SerializedName(SERIALIZED_NAME_3)
  private MatchV5MatchTimelineInfoFrameParticipantFrame _3;

  public static final String SERIALIZED_NAME_4 = "4";
  @SerializedName(SERIALIZED_NAME_4)
  private MatchV5MatchTimelineInfoFrameParticipantFrame _4;

  public static final String SERIALIZED_NAME_5 = "5";
  @SerializedName(SERIALIZED_NAME_5)
  private MatchV5MatchTimelineInfoFrameParticipantFrame _5;

  public static final String SERIALIZED_NAME_6 = "6";
  @SerializedName(SERIALIZED_NAME_6)
  private MatchV5MatchTimelineInfoFrameParticipantFrame _6;

  public static final String SERIALIZED_NAME_7 = "7";
  @SerializedName(SERIALIZED_NAME_7)
  private MatchV5MatchTimelineInfoFrameParticipantFrame _7;

  public static final String SERIALIZED_NAME_8 = "8";
  @SerializedName(SERIALIZED_NAME_8)
  private MatchV5MatchTimelineInfoFrameParticipantFrame _8;

  public static final String SERIALIZED_NAME_9 = "9";
  @SerializedName(SERIALIZED_NAME_9)
  private MatchV5MatchTimelineInfoFrameParticipantFrame _9;

  public static final String SERIALIZED_NAME_10 = "10";
  @SerializedName(SERIALIZED_NAME_10)
  private MatchV5MatchTimelineInfoFrameParticipantFrame _10;

  public MatchV5MatchTimelineInfoFrameParticipantFrames() {
  }

  public MatchV5MatchTimelineInfoFrameParticipantFrames _1(MatchV5MatchTimelineInfoFrameParticipantFrame _1) {
    this._1 = _1;
    return this;
  }

   /**
   * Get _1
   * @return _1
  **/
  @javax.annotation.Nonnull
  public MatchV5MatchTimelineInfoFrameParticipantFrame get1() {
    return _1;
  }

  public void set1(MatchV5MatchTimelineInfoFrameParticipantFrame _1) {
    this._1 = _1;
  }


  public MatchV5MatchTimelineInfoFrameParticipantFrames _2(MatchV5MatchTimelineInfoFrameParticipantFrame _2) {
    this._2 = _2;
    return this;
  }

   /**
   * Get _2
   * @return _2
  **/
  @javax.annotation.Nonnull
  public MatchV5MatchTimelineInfoFrameParticipantFrame get2() {
    return _2;
  }

  public void set2(MatchV5MatchTimelineInfoFrameParticipantFrame _2) {
    this._2 = _2;
  }


  public MatchV5MatchTimelineInfoFrameParticipantFrames _3(MatchV5MatchTimelineInfoFrameParticipantFrame _3) {
    this._3 = _3;
    return this;
  }

   /**
   * Get _3
   * @return _3
  **/
  @javax.annotation.Nonnull
  public MatchV5MatchTimelineInfoFrameParticipantFrame get3() {
    return _3;
  }

  public void set3(MatchV5MatchTimelineInfoFrameParticipantFrame _3) {
    this._3 = _3;
  }


  public MatchV5MatchTimelineInfoFrameParticipantFrames _4(MatchV5MatchTimelineInfoFrameParticipantFrame _4) {
    this._4 = _4;
    return this;
  }

   /**
   * Get _4
   * @return _4
  **/
  @javax.annotation.Nonnull
  public MatchV5MatchTimelineInfoFrameParticipantFrame get4() {
    return _4;
  }

  public void set4(MatchV5MatchTimelineInfoFrameParticipantFrame _4) {
    this._4 = _4;
  }


  public MatchV5MatchTimelineInfoFrameParticipantFrames _5(MatchV5MatchTimelineInfoFrameParticipantFrame _5) {
    this._5 = _5;
    return this;
  }

   /**
   * Get _5
   * @return _5
  **/
  @javax.annotation.Nonnull
  public MatchV5MatchTimelineInfoFrameParticipantFrame get5() {
    return _5;
  }

  public void set5(MatchV5MatchTimelineInfoFrameParticipantFrame _5) {
    this._5 = _5;
  }


  public MatchV5MatchTimelineInfoFrameParticipantFrames _6(MatchV5MatchTimelineInfoFrameParticipantFrame _6) {
    this._6 = _6;
    return this;
  }

   /**
   * Get _6
   * @return _6
  **/
  @javax.annotation.Nonnull
  public MatchV5MatchTimelineInfoFrameParticipantFrame get6() {
    return _6;
  }

  public void set6(MatchV5MatchTimelineInfoFrameParticipantFrame _6) {
    this._6 = _6;
  }


  public MatchV5MatchTimelineInfoFrameParticipantFrames _7(MatchV5MatchTimelineInfoFrameParticipantFrame _7) {
    this._7 = _7;
    return this;
  }

   /**
   * Get _7
   * @return _7
  **/
  @javax.annotation.Nonnull
  public MatchV5MatchTimelineInfoFrameParticipantFrame get7() {
    return _7;
  }

  public void set7(MatchV5MatchTimelineInfoFrameParticipantFrame _7) {
    this._7 = _7;
  }


  public MatchV5MatchTimelineInfoFrameParticipantFrames _8(MatchV5MatchTimelineInfoFrameParticipantFrame _8) {
    this._8 = _8;
    return this;
  }

   /**
   * Get _8
   * @return _8
  **/
  @javax.annotation.Nonnull
  public MatchV5MatchTimelineInfoFrameParticipantFrame get8() {
    return _8;
  }

  public void set8(MatchV5MatchTimelineInfoFrameParticipantFrame _8) {
    this._8 = _8;
  }


  public MatchV5MatchTimelineInfoFrameParticipantFrames _9(MatchV5MatchTimelineInfoFrameParticipantFrame _9) {
    this._9 = _9;
    return this;
  }

   /**
   * Get _9
   * @return _9
  **/
  @javax.annotation.Nullable
  public MatchV5MatchTimelineInfoFrameParticipantFrame get9() {
    return _9;
  }

  public void set9(MatchV5MatchTimelineInfoFrameParticipantFrame _9) {
    this._9 = _9;
  }


  public MatchV5MatchTimelineInfoFrameParticipantFrames _10(MatchV5MatchTimelineInfoFrameParticipantFrame _10) {
    this._10 = _10;
    return this;
  }

   /**
   * Get _10
   * @return _10
  **/
  @javax.annotation.Nullable
  public MatchV5MatchTimelineInfoFrameParticipantFrame get10() {
    return _10;
  }

  public void set10(MatchV5MatchTimelineInfoFrameParticipantFrame _10) {
    this._10 = _10;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchV5MatchTimelineInfoFrameParticipantFrames matchV5MatchTimelineInfoFrameParticipantFrames = (MatchV5MatchTimelineInfoFrameParticipantFrames) o;
    return Objects.equals(this._1, matchV5MatchTimelineInfoFrameParticipantFrames._1) &&
        Objects.equals(this._2, matchV5MatchTimelineInfoFrameParticipantFrames._2) &&
        Objects.equals(this._3, matchV5MatchTimelineInfoFrameParticipantFrames._3) &&
        Objects.equals(this._4, matchV5MatchTimelineInfoFrameParticipantFrames._4) &&
        Objects.equals(this._5, matchV5MatchTimelineInfoFrameParticipantFrames._5) &&
        Objects.equals(this._6, matchV5MatchTimelineInfoFrameParticipantFrames._6) &&
        Objects.equals(this._7, matchV5MatchTimelineInfoFrameParticipantFrames._7) &&
        Objects.equals(this._8, matchV5MatchTimelineInfoFrameParticipantFrames._8) &&
        Objects.equals(this._9, matchV5MatchTimelineInfoFrameParticipantFrames._9) &&
        Objects.equals(this._10, matchV5MatchTimelineInfoFrameParticipantFrames._10);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchV5MatchTimelineInfoFrameParticipantFrames {\n");
    sb.append("    _1: ").append(toIndentedString(_1)).append("\n");
    sb.append("    _2: ").append(toIndentedString(_2)).append("\n");
    sb.append("    _3: ").append(toIndentedString(_3)).append("\n");
    sb.append("    _4: ").append(toIndentedString(_4)).append("\n");
    sb.append("    _5: ").append(toIndentedString(_5)).append("\n");
    sb.append("    _6: ").append(toIndentedString(_6)).append("\n");
    sb.append("    _7: ").append(toIndentedString(_7)).append("\n");
    sb.append("    _8: ").append(toIndentedString(_8)).append("\n");
    sb.append("    _9: ").append(toIndentedString(_9)).append("\n");
    sb.append("    _10: ").append(toIndentedString(_10)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("1");
    openapiFields.add("2");
    openapiFields.add("3");
    openapiFields.add("4");
    openapiFields.add("5");
    openapiFields.add("6");
    openapiFields.add("7");
    openapiFields.add("8");
    openapiFields.add("9");
    openapiFields.add("10");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("1");
    openapiRequiredFields.add("2");
    openapiRequiredFields.add("3");
    openapiRequiredFields.add("4");
    openapiRequiredFields.add("5");
    openapiRequiredFields.add("6");
    openapiRequiredFields.add("7");
    openapiRequiredFields.add("8");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to MatchV5MatchTimelineInfoFrameParticipantFrames
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MatchV5MatchTimelineInfoFrameParticipantFrames.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MatchV5MatchTimelineInfoFrameParticipantFrames is not found in the empty JSON string", MatchV5MatchTimelineInfoFrameParticipantFrames.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MatchV5MatchTimelineInfoFrameParticipantFrames.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MatchV5MatchTimelineInfoFrameParticipantFrames` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MatchV5MatchTimelineInfoFrameParticipantFrames.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `1`
      MatchV5MatchTimelineInfoFrameParticipantFrame.validateJsonElement(jsonObj.get("1"));
      // validate the required field `2`
      MatchV5MatchTimelineInfoFrameParticipantFrame.validateJsonElement(jsonObj.get("2"));
      // validate the required field `3`
      MatchV5MatchTimelineInfoFrameParticipantFrame.validateJsonElement(jsonObj.get("3"));
      // validate the required field `4`
      MatchV5MatchTimelineInfoFrameParticipantFrame.validateJsonElement(jsonObj.get("4"));
      // validate the required field `5`
      MatchV5MatchTimelineInfoFrameParticipantFrame.validateJsonElement(jsonObj.get("5"));
      // validate the required field `6`
      MatchV5MatchTimelineInfoFrameParticipantFrame.validateJsonElement(jsonObj.get("6"));
      // validate the required field `7`
      MatchV5MatchTimelineInfoFrameParticipantFrame.validateJsonElement(jsonObj.get("7"));
      // validate the required field `8`
      MatchV5MatchTimelineInfoFrameParticipantFrame.validateJsonElement(jsonObj.get("8"));
      // validate the optional field `9`
      if (jsonObj.get("9") != null && !jsonObj.get("9").isJsonNull()) {
        MatchV5MatchTimelineInfoFrameParticipantFrame.validateJsonElement(jsonObj.get("9"));
      }
      // validate the optional field `10`
      if (jsonObj.get("10") != null && !jsonObj.get("10").isJsonNull()) {
        MatchV5MatchTimelineInfoFrameParticipantFrame.validateJsonElement(jsonObj.get("10"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MatchV5MatchTimelineInfoFrameParticipantFrames.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MatchV5MatchTimelineInfoFrameParticipantFrames' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MatchV5MatchTimelineInfoFrameParticipantFrames> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MatchV5MatchTimelineInfoFrameParticipantFrames.class));

       return (TypeAdapter<T>) new TypeAdapter<MatchV5MatchTimelineInfoFrameParticipantFrames>() {
           @Override
           public void write(JsonWriter out, MatchV5MatchTimelineInfoFrameParticipantFrames value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MatchV5MatchTimelineInfoFrameParticipantFrames read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MatchV5MatchTimelineInfoFrameParticipantFrames given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MatchV5MatchTimelineInfoFrameParticipantFrames
  * @throws IOException if the JSON string is invalid with respect to MatchV5MatchTimelineInfoFrameParticipantFrames
  */
  public static MatchV5MatchTimelineInfoFrameParticipantFrames fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MatchV5MatchTimelineInfoFrameParticipantFrames.class);
  }

 /**
  * Convert an instance of MatchV5MatchTimelineInfoFrameParticipantFrames to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

