/*
 * Riot API
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([view file](../openapi-3.0.0.json), [ui select](?url=../openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([view file](../openapi-3.0.0.min.json), [ui select](?url=../openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([view file](../openapi-3.0.0.yml), [ui select](?url=../openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([view file](../openapi-3.0.0.min.yml), [ui select](?url=../openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([view file](../swaggerspec-2.0.json), [ui select](?url=../swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([view file](../swaggerspec-2.0.min.json), [ui select](?url=../swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([view file](../swaggerspec-2.0.yml), [ui select](?url=../swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([view file](../swaggerspec-2.0.min.yml), [ui select](?url=../swaggerspec-2.0.min.yml)) ## Other Files - Missing DTOs: [`missing.json`](../missing.json) - Routes Table: [`routesTable.json`](../routesTable.json) - [Enum Files](../enums/) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.com/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * The version of the OpenAPI document: 879affafe206ccc5b48127e68c0bd466fcc73c84
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.pajonti.sejuapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import fr.pajonti.sejuapi.invoker.JSON;

/**
 * ValMatchV1DamageDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-14T18:28:23.553111400+01:00[Europe/Paris]", comments = "Generator version: 7.4.0")
public class ValMatchV1DamageDto {
  public static final String SERIALIZED_NAME_RECEIVER = "receiver";
  @SerializedName(SERIALIZED_NAME_RECEIVER)
  private String receiver;

  public static final String SERIALIZED_NAME_DAMAGE = "damage";
  @SerializedName(SERIALIZED_NAME_DAMAGE)
  private Integer damage;

  public static final String SERIALIZED_NAME_LEGSHOTS = "legshots";
  @SerializedName(SERIALIZED_NAME_LEGSHOTS)
  private Integer legshots;

  public static final String SERIALIZED_NAME_BODYSHOTS = "bodyshots";
  @SerializedName(SERIALIZED_NAME_BODYSHOTS)
  private Integer bodyshots;

  public static final String SERIALIZED_NAME_HEADSHOTS = "headshots";
  @SerializedName(SERIALIZED_NAME_HEADSHOTS)
  private Integer headshots;

  public ValMatchV1DamageDto() {
  }

  public ValMatchV1DamageDto receiver(String receiver) {
    this.receiver = receiver;
    return this;
  }

   /**
   * PUUID
   * @return receiver
  **/
  @javax.annotation.Nonnull
  public String getReceiver() {
    return receiver;
  }

  public void setReceiver(String receiver) {
    this.receiver = receiver;
  }


  public ValMatchV1DamageDto damage(Integer damage) {
    this.damage = damage;
    return this;
  }

   /**
   * Get damage
   * @return damage
  **/
  @javax.annotation.Nonnull
  public Integer getDamage() {
    return damage;
  }

  public void setDamage(Integer damage) {
    this.damage = damage;
  }


  public ValMatchV1DamageDto legshots(Integer legshots) {
    this.legshots = legshots;
    return this;
  }

   /**
   * Get legshots
   * @return legshots
  **/
  @javax.annotation.Nonnull
  public Integer getLegshots() {
    return legshots;
  }

  public void setLegshots(Integer legshots) {
    this.legshots = legshots;
  }


  public ValMatchV1DamageDto bodyshots(Integer bodyshots) {
    this.bodyshots = bodyshots;
    return this;
  }

   /**
   * Get bodyshots
   * @return bodyshots
  **/
  @javax.annotation.Nonnull
  public Integer getBodyshots() {
    return bodyshots;
  }

  public void setBodyshots(Integer bodyshots) {
    this.bodyshots = bodyshots;
  }


  public ValMatchV1DamageDto headshots(Integer headshots) {
    this.headshots = headshots;
    return this;
  }

   /**
   * Get headshots
   * @return headshots
  **/
  @javax.annotation.Nonnull
  public Integer getHeadshots() {
    return headshots;
  }

  public void setHeadshots(Integer headshots) {
    this.headshots = headshots;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValMatchV1DamageDto valMatchV1DamageDto = (ValMatchV1DamageDto) o;
    return Objects.equals(this.receiver, valMatchV1DamageDto.receiver) &&
        Objects.equals(this.damage, valMatchV1DamageDto.damage) &&
        Objects.equals(this.legshots, valMatchV1DamageDto.legshots) &&
        Objects.equals(this.bodyshots, valMatchV1DamageDto.bodyshots) &&
        Objects.equals(this.headshots, valMatchV1DamageDto.headshots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receiver, damage, legshots, bodyshots, headshots);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValMatchV1DamageDto {\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    damage: ").append(toIndentedString(damage)).append("\n");
    sb.append("    legshots: ").append(toIndentedString(legshots)).append("\n");
    sb.append("    bodyshots: ").append(toIndentedString(bodyshots)).append("\n");
    sb.append("    headshots: ").append(toIndentedString(headshots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("receiver");
    openapiFields.add("damage");
    openapiFields.add("legshots");
    openapiFields.add("bodyshots");
    openapiFields.add("headshots");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("receiver");
    openapiRequiredFields.add("damage");
    openapiRequiredFields.add("legshots");
    openapiRequiredFields.add("bodyshots");
    openapiRequiredFields.add("headshots");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ValMatchV1DamageDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ValMatchV1DamageDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ValMatchV1DamageDto is not found in the empty JSON string", ValMatchV1DamageDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ValMatchV1DamageDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ValMatchV1DamageDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ValMatchV1DamageDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("receiver").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `receiver` to be a primitive type in the JSON string but got `%s`", jsonObj.get("receiver").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ValMatchV1DamageDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ValMatchV1DamageDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ValMatchV1DamageDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ValMatchV1DamageDto.class));

       return (TypeAdapter<T>) new TypeAdapter<ValMatchV1DamageDto>() {
           @Override
           public void write(JsonWriter out, ValMatchV1DamageDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ValMatchV1DamageDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ValMatchV1DamageDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ValMatchV1DamageDto
  * @throws IOException if the JSON string is invalid with respect to ValMatchV1DamageDto
  */
  public static ValMatchV1DamageDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ValMatchV1DamageDto.class);
  }

 /**
  * Convert an instance of ValMatchV1DamageDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

